services:
  ################################ POSTGRES #####################################
  postgres:
    image: postgres:15
    container_name: task-hub-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nimda
      POSTGRES_DB: tasks_schema
    ports:
      - "5432:5432"
    volumes:
      - ./task-hub-db:/var/lib/postresql/data
      - task-hub-db:/var/lib/postresql/data

  spring-task-hub:
    image: spring-task-hub
    container_name: task-hub-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://task-hub-db:5432/tasks_schema
    depends_on:
      - postgres

volumes:
  task-hub-db: